// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvmoecwcsceepcunxzmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bW9lY3djc2NlZXBjdW54em1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NjkwNTIsImV4cCI6MjA4ODA0NTA1Mn0.uKphHL9-a1sMQc-rkjBjxKzJ2QHDZ-LCOiF9m7wNRto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});